# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-09-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='best_entity',
            field=models.ForeignKey(db_column='best_entity', help_text='The best entity link for this mention', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='corenlp.Entity'),
        ),
    ]
