# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-09-05 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0002_auto_20160904_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='source',
        ),
    ]
