# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-09-05 05:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0003_remove_document_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 37, 21, 749760), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 37, 21, 752170), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 37, 21, 752950), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 37, 21, 754022), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 37, 21, 750385), help_text='Keeps track of when this sentence was added'),
        ),
    ]
