# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-09-05 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0004_auto_20160905_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 38, 6, 989161, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 38, 6, 991793, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 38, 6, 992379, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 38, 6, 993490, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 5, 38, 6, 990696, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
    ]
