# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-09-07 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0003_remove_document_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='canonical_gloss',
            field=models.TextField(help_text='Raw text representation of the mention', null=True),
        ),
    ]
