# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-09-07 05:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0005_auto_20160905_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='canonical_gloss',
            field=models.TextField(help_text='Raw text representation of the mention', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 5, 27, 15, 636195, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 5, 27, 15, 638114, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 5, 27, 15, 638666, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 5, 27, 15, 639941, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 7, 5, 27, 15, 637249, tzinfo=utc), help_text='Keeps track of when this sentence was added'),
        ),
    ]
