# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0007_auto_20160910_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='canonical_mention',
            field=models.ForeignKey(help_text='A link to the canonical mention id', null=True, on_delete=django.db.models.deletion.CASCADE, to='corenlp.Mention'),
        ),
    ]
