# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corenlp', '0008_mention_canonical_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='mention',
            name='parent_mention',
            field=models.ForeignKey(help_text='Identifies if this mention is contained in another one.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='corenlp.Mention'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='canonical_mention',
            field=models.ForeignKey(help_text='A link to the canonical mention id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='corenlp.Mention'),
        ),
    ]
